services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bookshelf-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="file://app/data/sqlite.db"
    volumes:
      - .:/app
      - ./data:/app/data
      - /app/node_modules
      - /app/.next
    command: sh -c "npx prisma generate && npm run dev"